### ISSUE TITLE
xScheduledTask - Cannot convert value "Indefinitely" to type "System.DateTime"

### ISSUE THREAD

**Issue by ahebert** [PowerShell/xComputerManagement#110]
**Details of the scenario you tried and the problem that is occurring:**
        xScheduledTask DeploymentTask
        {
            Ensure = "Present"
            Enable = $true
            TaskName = $Node.TaskName
            ActionExecutable = $Node.TaskExecutable
            ScheduleType = "Once"
            StartTime = [datetime]::Now.AddMinutes($Node.TaskIntervalMinutes)
            RepetitionDuration = 'Indefinitely'
            RepeatInterval     = '00:15:00'
            MultipleInstances = "IgnoreNew"
        }

**Getting deployment exception:**

"The DSC Extension received an incorrect input: Compilation errors occurred while processing configuration '*****'. Please review the errors reported in error stream and modify your configuration code appropriately. System.Management.Automation.ParameterBindingArgumentTransformationException error processing property 'RepetitionDuration' OF TYPE 'xScheduledTask': Cannot process argument transformation on parameter 'd'. Cannot convert value \"Indefinitely\" to type \"System.DateTime\". Error: \"The string was not recognized as a valid DateTime. There is an unknown word starting at index 0.\"

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016, DSC: 2.71.1.0, PSVersion 5.1.14393.1770

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev branch version.

**Comment by PlagueHO** [comment]
Hi there @ahebert - thanks for submitting this. Can you tell me which version of the xComputerManagement resource you are using?

**Comment by ahebert** [comment]
ModuleVersion = '2.1.0.0'

**Comment by PlagueHO** [comment]
No worries! We only added the 'indefinitely' support in v3.0.0.0. Please let me know if this resolves the issue! :grin:

**Comment by ahebert** [comment]
The non-issue is resolved. Apologies for the fire drill.

**Comment by PlagueHO** [comment]
No problemo. Thanks for closing!
