### ISSUE TITLE
xScheduledTask: Set-ScheduleTask instead of UnRegister/Register

### ISSUE THREAD

**Issue by GitBadSanta** [PowerShell/xComputerManagement#134]
We try to update schedule task through DSC with "Do not start new instance" setting and we are facing the following issue:

If the task is running, the unregister/register update will let an orphan process running and the new scheduled task will start even if the "Do not start new instance" is set, which is normal because the task has been re-created, but is not acceptable for an update mechanism. 

A Set-ScheduleTask on the other hand has the correct behavior : waiting for the previous instance to stop before launching the new one.

We did some tests and obtain good results, but we'd like to know your thoughts on how difficult it would be to correctly integrate the Set-ScheduleTask for updates.

Thanks.

**Comment by GitBadSanta** [comment]
Hi, 
A first increment on how this could be done : 
https://github.com/GitBadSanta/xComputerManagement/commit/a5aba4bb31ba75c067cb87a0900b78e9b1a372ea

**Comment by PlagueHO** [comment]
Ah I see @GitBadSanta - that is a good solution you've proposed there! I think we should definitely incorporate this. Do you know if this works on Windows Server 2012/R2 and Windows Server 2016? We might have to make some minor tweaks to ensure it works on both versions. So I'll see if I can do some work on this over the weekend. Or do you want to submit a PR for this (which we'd be grateful to accept :grin: )?

**Comment by PlagueHO** [comment]
This one has now been fixed/merged. Thanks for your help @GitBadSanta !
