### ISSUE TITLE
Cannot change computer name using xComputer resource

### ISSUE THREAD

**Issue by amitsara** [PowerShell/xComputerManagement#14]
configuration foo
{
    Import-dscresource -ModuleName xComputerManagement
    xComputer x
    {
        Name = 'amitsara-PC2'
    }
}
 
foo
Start-DscConfiguration -path .\foo -wait -force -Verbose  
 
 
PS C:\Scenario\TwoTierPKI> F:\Users\Administrator\Desktop\Untitled1.ps1
 
    Directory: C:\Scenario\TwoTierPKI\foo
 
Mode                LastWriteTime         Length Name                                                                                                                    
----                -------------         ------ ----                                                                                                                    
-a----       10/21/2015   1:18 PM           1838 localhost.mof                                                                                                           
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespace
Name' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer AMITSARA-PC2 with user sid S-1-5-21-2127521184-1604012920-1887927527-13139468.
VERBOSE: [AMITSARA-PC2]: LCM:  [ Start  Set      ]
VERBOSE: [AMITSARA-PC2]: LCM:  [ Start  Resource ]  [[xComputer]x]
VERBOSE: [AMITSARA-PC2]: LCM:  [ Start  Test     ]  [[xComputer]x]
VERBOSE: [AMITSARA-PC2]:                            [[xComputer]x] Checking if computer name is amitsara-PC2
VERBOSE: [AMITSARA-PC2]: LCM:  [ End    Test     ]  [[xComputer]x]  in 0.1250 seconds.
The PowerShell DSC resource C:\Program Files\WindowsPowerShell\Modules\xComputerManagement\DscResources\MSFT_xComputer returned results in a format that is not valid. 
The results from running Test-TargetResource must be the boolean value True or False.
    + CategoryInfo          : InvalidResult: (:) [], CimException
    + FullyQualifiedErrorId : TestTargetResourceInvalidResultFormat
    + PSComputerName        : localhost
 
VERBOSE: [AMITSARA-PC2]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotImplemented: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 7
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.388 seconds

**Comment by KarolKaczmarek** [comment]
Followed up with @amitsara and this can be closed as he determined both versions of this module from PowerShell gallery and github are working as expected.
