### ISSUE TITLE
Computer Name length

### ISSUE THREAD

**Issue by dcrreynolds** [PowerShell/xComputerManagement#15]
Computer names longer than 15 chars will have their name truncated upon rename. After this, test-targetResource will continually return false, and set-targetResource will continually throw an exception. It would be nice to add a name length check before performing the rename.

**Comment by leshkinski** [comment]
I would say that the all resource functions need to be aware of the 15 character limitation and automatically truncate the name to 15 characters. This will ensure correct resource functionality and compatibility with windows hostname restrictions. 

Alternative is to throw an exception in both, Set and Test, and expect the user to correct his/her configuration error. I'm a fan of this approach, if that counts for anything :)

**Comment by dcrreynolds** [comment]
I am a fan of throwing an exception in both Set and Test. It would seem strange to truncate without informing the user and could cause wide spread naming issues. I will add the check and some test cases.

**Comment by KarolKaczmarek** [comment]
agree, performing parameter value check and throwing early is the way to go here

**Comment by dcrreynolds** [comment]
Adding a ValidationScript at the parameter seemed the cleanest way to add this check, however, the exception thrown is cryptic if the user is not familiar with regex.
