### ISSUE TITLE
Test-DSCResource throws invalid response type

### ISSUE THREAD

**Issue by 1RedOne** [PowerShell/xComputerManagement#17]
Noticed that when I change my system name using this module, but make no other changes, that I get a fatal error during Test-TargetResource phase.  

VERBOSE: [FOXDC]: LCM:  [ End    Test     ]  [[xComputer]NewNameAndWorkgroup]  in 0.0160 seconds.
The PowerShell DSC resource C:\Program Files\WindowsPowerShell\Modules\xComputerManagement\DscResources\MSFT_xComputer returned results in a format that is not valid. The results 
from running Test-TargetResource must be the boolean value True or False.
    + CategoryInfo          : InvalidResult: (:) [], CimException
    + FullyQualifiedErrorId : TestTargetResourceInvalidResultFormat
    + PSComputerName        : localhost

**Comment by PlagueHO** [comment]
@1RedOne - I think this one has been fixed. I can't replicate it in the current version.

So I'll close this. Feel free to reopen it if it isn't fixed.
