### ISSUE TITLE
Add Support for Offline Domain Join (ODJ)

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xComputerManagement#23]
This is primarily to support joining Nano Servers to a Domain, but it should work for any server as well.

Note: The ```*-Computer``` (e.g. Add-Computer, Rename-Computer) are not available in Nano Server.

Option 1:
Add an optional ODJFile parameter to the xComputer resource:
```
[write,description("The path to an Offline Domain Join blob file.")] string ODJFile;
```
If this is passed then instead of using the normal code path it could check for domain membership and if missing call out to DJOIN.EXE (there is no PowerShell equivalent to DJOIN.EXE that I know of).

Option 2:
Create an entirely new resource (e.g. xODJ) for performing ODJ that will only perform the join from a blob and nothing else (no computer rename etc).

I prefer Option 2 because it means no change to existing resources.

I'm happy to implement this (I need it for one of my projects) but would love feed back on what people think is the best way to go.

The Nano info is also based around TP4, so what is supported by Nano might change with future releases. But ODJ should still be something that is needed for non-Nano Servers.

**Comment by tysonjhayes** [comment]
Option 2 makes the most amount of sense to me.

**Comment by PlagueHO** [comment]
Thanks @tysonjhayes - I'll go with that option then :+1:
