### ISSUE TITLE
xScheduledTask: Add Triggers At log on / At startup

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xComputerManagement#34]
Thank you for creating the Scheduled Task resource. It would be nice if it could support the Triggers 'At log on' and 'At startup'.

**Comment by 1800Zeta** [comment]
Just to "upvote" this option, its something I'm going to have to work on externally for now

**Comment by DamianBis** [comment]
I also really need this. i'm happy to work on this and do a pull request.

**Comment by markallisongit** [comment]
Yep, would love to have this.

**Comment by typozh** [comment]
I would also vote for this! Thanks.
