### ISSUE TITLE
 xComputer Test-TargetResource BUG

### ISSUE THREAD

**Issue by SuperMarioo** [PowerShell/xComputerManagement#44]
GetComputerDomain Function 

Consistent Check is failing as System account doesn't have AD Permissions 

([System.DirectoryServices.ActiveDirectory.Domain]::GetComputerDomain()).Name

Test should be changed .

**Comment by PlagueHO** [comment]
Wow - this has been outstanding for quite a while. I'll try and look at this one next.

**Comment by markgossa** [comment]
Line 568 from

$domainName = ([System.DirectoryServices.ActiveDirectory.Domain]::GetComputerDomain()).Name

to

$domainName = (Get-WmiObject -Class win32_computersystem).Domain

Want to assign this to me?

**Comment by PlagueHO** [comment]
Hi @markgossa - sure thing! Definitely keen for the help :grin:. I can't set the "assigned to" to you because GitHub won't let me (I can only assign it to Repo or Org admins). But I won't work on it - I'll leave it to you and mark it as In Progress.

**Comment by markgossa** [comment]
Hi @PlagueHO - thanks. It'll be my first contribution on GitHub in fact.

**Comment by PlagueHO** [comment]
@markgossa - that is awesome :grin: ! If you have any questions at all just let me know here and I'll give you a hand. We are really glad to have the help.

**Comment by markgossa** [comment]
Hi @PlagueHO, did you see my updated code in pull request 113? I've written some pester tests and corrected the code in MSFT_xComputer.psm1. There is a conflict so it can't be merged automatically but it's just a simple merge on readme.md.

**Comment by PlagueHO** [comment]
Hi @markgossa - sorry about the delay, I took a short holiday :grin: So I'm just now catching up on all the PR's etc. I'll try and get to this one today.

**Comment by markgossa** [comment]
@PlagueHO - No problem at all! I was also on holiday but got a little bored once or twice so did some work on this on my flight and in the hotel in the evenings. I'll make the changes and get them sent over. Thanks! :-)
