### ISSUE TITLE
xScheduledTask failed

### ISSUE THREAD

**Issue by twarnick** [PowerShell/xComputerManagement#45]
the scheduledTask created successfully, but the verify failed.

here my scheduleTask:

xScheduledTask Task_ddd_sync {
    ActionExecutable = "C:\Program Files (x86)\Robocopy\ddd_sync.cmd"
    RepeatInterval = 60
    ScheduleType = "Minutes"
    TaskName = "ddd-sync"
    DependsOn = '[xUser]TachographUser'
    Ensure = "Present"
    ExecuteAsCredential = $TachographUserCred
    StartTime = "03:00"
}

**Comment by twarnick** [comment]
The Error Message in Event log 
Source:Microsoft-Windows-Desired State Configuration/Operational:

Job {80BBADD1-6974-11E6-8C2A-000D3A2034C0} : 
MIResult: 1
Error Message: Cannot create a file when that file already exists.

Message ID: HRESULT 0x800700b7,Register-ScheduledTask
Error Category: 20
Error Code: 20
Error Type: MI

**Comment by PlagueHO** [comment]
Closed by #62
