### ISSUE TITLE
Move PowerPlan resource from xSQLServer module to xComputerManagement 

### ISSUE THREAD

**Issue by johlju** [PowerShell/xComputerManagement#46]
In the xSQLServer module there is currently a resource called xSqlServerPowerPlan. A suggestion was raised (issue PowerShell/xSQLServer#129 ) to move that to the xComputerManagement module instead since it is not just connected to SQL. And at the same time rename the resource to xPowerPlan. 

Any thoughts on this?

I'm happy to start the process by sending in a PR to this module.

**Comment by ArieHein** [comment]
I remember such a module in the old stackexchange repo from powershell.org that also had a pagefile resource among other. Always thought it was already merged back to the DSC resources.

https://github.com/PowerShellOrg/StackExchangeResources/tree/master/DSCResources


should probably open a new issue for the pagefile resource then.

**Comment by johlju** [comment]
@ArieHein sounds like a good idea to open an new issue for a pagefile resource so someone can submit a resource for that to this repo.

**Comment by johlju** [comment]
This was resolved in merge PR #47
