### ISSUE TITLE
xComputerManagement does not meet HQRM requirements

### ISSUE THREAD

**Issue by lfshr** [PowerShell/xComputerManagement#51]
xComputerManagement does not meet HQRM requirements. This issue is here for discussions and PRs related to the readiness of xComputerManagement gaining HQRM status.

**Comment by LiamFisher92** [comment]
Work to do credit kwirkykat:

> 2 of the resources still need integration tests. I see some issues PSSA will flag in the resource code (there > are no verbose messages in xComputer). This module should probably also be set up for localized strings > for the verbose messages especially as we are discussing adding SystemLocale here.
>
> I would say this module is closer than most to becoming high quality since it does already have unit tests, > but it definitely still needs some polishing.

**Comment by PlagueHO** [comment]
This issue has been superseded by #94. So I'll close this one.
