### ISSUE TITLE
xComputer changes settings on a computer with Certification Authority Service installed.

### ISSUE THREAD

**Issue by LiamFisher92** [PowerShell/xComputerManagement#52]
xComputer will currently attempt to change the settings on a computer with certificate authority (which is not supported by Windows as far as I'm aware).

Is this something that should change? Got some code here that'll run a test, let me know if you want a PR in.

**Comment by PlagueHO** [comment]
Hi @TheFish92 - I'm not sure I understand. What settings does it change? Sorry if I'm being dumb :grin:

**Comment by TheFish92** [comment]
Hi @PlagueHO, during tests xComputer changed the computer name of the CA server. (If you try and do this manually you're stopped in your tracks as you're not meant to do it). I've not tested any of the other functionality features of xComputer. May be something to test! :)

**Comment by TheFish92** [comment]
@PlagueHO would changing the CA's computer name not break all certificates issued by that CA? That's the issue. Sorry for not being as clear 🤓

**Comment by iainbrighton** [comment]
So this is an issue ONLY when changing the name of a CA server and nothing to do with changing the name of a computer that has certificates issued by a CA? I can see how that wouldn't end well!

I've never tried it, but presumably Windows stops you doing this via the GUI? Nothing like automating the stupid :P

**Comment by TheFish92** [comment]
Exactly! Now for the political battle, is it Rename-Computer than should change, or xComputer! 😋

**Comment by TheFish92** [comment]
And yeah, the UI stops you in your tracks.

**Comment by PlagueHO** [comment]
@TheFish92, @iainbrighton - ah right! Now I understand what you mean.

Wouldn't similar problems happen with other workloads? Where would we draw the line on what to prevent and what not? I can think of at least 3 or 4  other workloads or situations that renaming a computer would cause damage to the system.

I'm not sure it is the job of DSC resources to prevent a user from creating configs that could damage their system. The usual workflow used to create and deploy DSC configurations should always contain a "test" step where the DSC configuration is tested to ensure it produces the desired results. Deploying a workload without first testing that it doesn't result in a configuration that corrupts a node or environment is careless.

But that is just my 2c. :grin:

**Comment by LiamFisher92** [comment]
@PlagueHO Fair point. We could still display a warning of some sort though? Not every developer is going to understand the ramifications of renaming a CA. I'll close this for now though.

Liam
