### ISSUE TITLE
xComputer should support Offline Domain Join Request file to join domain

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xComputerManagement#56]

**Comment by PlagueHO** [comment]
@TravisEz13 - do you mean move the function from xOfflineDomainJoin into xComputer?

**Comment by TravisEz13** [comment]
I think I do... I open I did not find xOfflineDomainJoin because I assumed it would be in xComputer (even though I think I reviewed it).

It would probably be a breaking change but the schema is all wrong anyway... xComputer should be a single instance resource.

**Comment by PlagueHO** [comment]
Hi @TravisEz13 - I just realized that this one should be able to be closed as I completed this a while back now.
