### ISSUE TITLE
Ability to Set OU

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xComputerManagement#6]
I'd like to be able to set the OU on domain join and move the AD Object if possible. While I'm happy to write this myself I wanted to know what dependencies this resource would be willing to take. For example there is a Move-ADObject if we require the AD Module to be installed.  This would probably be the easiest requirement and the move powershell like.

**Comment by PrahlM93** [comment]
Hi,
I made a pull request with code that allows you to specify the OU when joining to the domain:
https://github.com/PowerShell/xComputerManagement/pull/13

We'll see if Microsoft accepts it, but you can use it for the time being.

**Comment by MarkDordoy-JustEat** [comment]
Id like to see this issue resolved as this functionality would be good to use. @PrahlM93 has Microsoft said anything about merging it?

**Comment by PrahlM93** [comment]
@MarkDordoy-JustEat nothing yet. @tysonjhayes works for Microsoft but still seems to be trying to get someone else to look at it.

**Comment by tysonjhayes** [comment]
Merged. Sorry about the delay here.

**Comment by MCrank** [comment]
Woohoo!  Thanks @tysonjhayes Much appreciated
