### ISSUE TITLE
Computer Description in xComputer

### ISSUE THREAD

**Issue by Outek** [PowerShell/xComputerManagement#67]
It would be nice, if i can set the computer description in the module xComputer.

**Comment by nyanhp** [comment]
Sounds interesting @Outek! I will develop it in https://github.com/nyanhp/xComputerManagement, branch 'feature/descriptionInxComputer'.

**Comment by PlagueHO** [comment]
Are you still planning on implementing this one @nyanhp ? If so I'll mark it as in progress.
