### ISSUE TITLE
xComputer JoinDomain fails when server is already in domain

### ISSUE THREAD

**Issue by nilsvbsol** [PowerShell/xComputerManagement#68]
Resource fails with fatal error if the computer already is in the domain.
The test should pick this up, which now it doesn't and hence throws a fatal exception when attempting to join the domain again.

**Error:** 
Cannot add computer 'x' to domain 'y' because it is already in that domain.
    + CategoryInfo          : InvalidOperation: (x:) [], CimException
    + FullyQualifiedErrorId : AddComputerToSameDomain,Microsoft.PowerShell.Commands.AddComputerCommand
    + PSComputerName        : localhost

**Comment by Identitry** [comment]
You are probably using NetBios domain name when joining but xComputer uses fully qualified domain name internally that unfortunately triggs a new join that will fail.

**Comment by PlagueHO** [comment]
Hi @nilsvbsol - @Identitry is quite correct I think. There is a PR going through at the moment that will resolve this:
https://github.com/PowerShell/xComputerManagement/pull/76
