### ISSUE TITLE
Error when specifying no Domain or Workgroup Name

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xComputerManagement#7]
When supplying a configuration to just set the computer's name - without specifying a Domain or Workgroup name - the Test-TargetResource method fails. The first Test-TargetResource fails as expected as the computer name is incorrect.

However, after the machine has been renamed correctly and rebooted, all subsequent Test-TargetResource calls fail as the method does not return $true or $false!

**Comment by TravisEz13** [comment]
fixed in above commit
