### ISSUE TITLE
xScheduledTask - Add additional time-based triggers

### ISSUE THREAD

**Issue by michaelsainz** [PowerShell/xComputerManagement#70]
Looking through the xScheduledTask DSC resource and I'm noticing that there is no time triggers based upon "monthly", "yearly" or "one time". Can we get this added as a potential enhancement? The ScheduledTasks PowerShell module supports these I believe.

This came about as a need to run some tasks for OS image generation that happen every 2nd Tuesday of the month.

**Comment by ChrisLGardner** [comment]
#69 should fix this, I believe @PlagueHO or someone else just needs to review it when they get a chance (I might try my hand at it if I find time).

**Comment by PlagueHO** [comment]
Cool! Thanks @ChrisLGardner - this has been merged now. @michaelsainz - any chance you could check if this resolves your issue? The new version won't be released till next month I think, but you can try out the Dev branch if you're interested.

**Comment by PlagueHO** [comment]
I'm going to close this one now. @michaelsainz - if this hasn't addressed your requirement, please feel free to reopen this one. Thanks!
