### ISSUE TITLE
xScheduleTask: Cannot disable already present tasks

### ISSUE THREAD

**Issue by johlju** [PowerShell/xComputerManagement#74]
It's not possible to disable already present tasks because it needs to set required parameters that should not be changed (and might be unknown per target node). 

```
        xScheduledTask 'DisableMyTask'
        {
           TaskName = 'MyTask'
           TaskPath = '\Company'
           Enable = $false
        }
```

**Comment by PlagueHO** [comment]
Hi @johlju - ah - I see. You're talking about the `ActionExecutable` and `ScheduleType` parameters being required parameters. I'll see what I can do - how urgent is this one?

**Comment by johlju** [comment]
Not urgent at all for me. Worked around it by using Script-resource instead. But rather use this when it is resolved.

**Comment by PlagueHO** [comment]
Hi @johlju - I'll try to get onto this one once PR #98 has been merged.

**Comment by johlju** [comment]
Sounds great. I hope it will be a small change :) I can review when you are done :)

**Comment by matt6697** [comment]
Issue is the same for deleting existing tasks. The following DSC action fails requiring ActionExecutable and ScheduleType parameters.

Fix needed to automate optimization of Citrix XenDesktop and Microsoft RDS Virtual Desktop Infrastructure master images as described in [https://virtualfeller.com/2017/05/04/optimize-vdi-windows-10-scheduled-tasks-original-anniversary-and-creator-updates/](url)

xScheduledTask 'DeleteMyTask'
        {
           TaskName = 'MyTask'
           TaskPath = '\Company'
           Ensure= 'Absent'
        }

Tasks like Microsoft\Windows\Application Experience\ProgramDataUpdater don't have a valid ScheduleType for the xScheduledTask DSC resource. Executing the same DSC action while setting the ActionExecutable and ScheduleType values also fails with a **Trigger type $_ not recognized** as the ScheduleType is not one of the ScheduleTypes defined in the switch/case of the GET function.

```
switch ($trigger.CimClass.CimClassName)
        {
            'MSFT_TaskTimeTrigger'
            {
                $returnScheduleType = 'Once'
                break
            }

            'MSFT_TaskDailyTrigger'
            {
                $returnScheduleType = 'Daily'
                break
            }

            'MSFT_TaskWeeklyTrigger'
            {
                $returnScheduleType = 'Weekly'
                break
            }

            'MSFT_TaskBootTrigger'
            {
                $returnScheduleType = 'AtStartup'
                break
            }

            'MSFT_TaskLogonTrigger'
            {
                $returnScheduleType = 'AtLogon'
                break
            }

            default
            {
                New-InvalidArgumentException -Message "Trigger type $_ not recognized." -ArgumentName CimClassName
            }
}
```

**Comment by ttdgcp** [comment]
@PlagueHO Hey Daniel, I'm running into issues trying to use DSC and xScheduleTask to delete the "Xbox" scheduled tasks that Server 2016 creates... (I know, right?)... I was wondering if you have any cycles to take a look at the necessary changes to support deleting these tasks?

From what I'm able to glean, the ActionExecutable and ScheduleType parameters being required parameters is what is causing this issue... perhaps we can make them not required when deleting?

If there is any further detail or assistance I can provide, please let me know!

**Comment by PlagueHO** [comment]
Hi @ttdgcp - Now that I've finished updating this module to HQRM I'll begin working on the features like this one. I actually started this a little while back so I'll try and work on this one this weekend (as well as some stuff on WsManDsc).

**Comment by matt6697** [comment]
@PlagueHO : Planning to rebuild my https://github.com/puppetlabs/puppetlabs-dsc fork with up to date powershell dsc modules (including sqlserverdsc update). When do you think you'll gonna be able to release the modifications required for scheduled task removal ? Fix needed for https://github.com/virtualdesktopdevops/xd7vda.

**Comment by PlagueHO** [comment]
Hi @matt6697 - this is in progress but I haven't managed to finish it yet (still working on updating the tests and other fun stuff like that). I'm hoping to get some free time this week to complete it. Sorry about taking so long!

**Comment by PlagueHO** [comment]
Nearly finished now. I have completed all the new tests required for this change. Just need to make the pass :wink: . Still aim to have this complete over the next couple of days.

Note: This change will be a breaking change because I'm going to have to remove some fields from the `Get-TargetResource` because of making some of the fields now optional. So a new major version of the resource module will be released.

**Comment by matt6697** [comment]
@PlagueHO : Hi Daniel, thanks for the update :-)

**Comment by PlagueHO** [comment]
Almost there! Should have the PR submitted tomorrow. New integration tests completed and passing, but unit tests are still failing. Need to increase the unit test coverage on the new code I added.
